Repository rospogrigio/localtuya, pull requests merged in 2020-10, with the labels that each got.

#84 Fix broken status for 0d devices
  custom_components/localtuya/common.py
  custom_components/localtuya/pytuya/__init__.py
Labels: bug

#92 Fix bugs in pytuya
  custom_components/localtuya/pytuya/__init__.py
Labels: bug, enhancement

#102 Add debug log instructions to readme
  README.md
Labels: documentation

#81 Cover uppercase and new commands
  README.md
  custom_components/localtuya/__init__.py
  custom_components/localtuya/const.py
  custom_components/localtuya/cover.py
  custom_components/localtuya/translations/en.json
  info.md
Labels: enhancement

#107 Fix status exception when no payload
  custom_components/localtuya/pytuya/__init__.py
Labels: bug

#90 Add support for HSV encoded color lights
  custom_components/localtuya/common.py
  custom_components/localtuya/const.py
  custom_components/localtuya/light.py
  custom_components/localtuya/translations/en.json
Labels: enhancement
